---
apiVersion: v1
kind: Service
metadata:
  name: global-triangles-backend
spec:
  selector:
    app: global-triangles-backend
  ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: global-triangles-backend
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: global-triangles-backend
            port:
              number: 3000